name: Deploy Doxygen Docs
on:
  push:
    branches:
      - main

permissions:
  contents: write   # 给 GitHub Actions 提供对仓库内容的写入权限

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Generate Docs
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_ACTION_FEDIS_DOXYGEN }}
          publish_dir: ./docs/html
